//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Act11.WSCS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCS.WSCSSoap")]
    public interface WSCSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento matricula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insersion", ReplyAction="*")]
        Act11.WSCS.InsersionResponse Insersion(Act11.WSCS.InsersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insersion", ReplyAction="*")]
        System.Threading.Tasks.Task<Act11.WSCS.InsersionResponse> InsersionAsync(Act11.WSCS.InsersionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento matricula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificacion", ReplyAction="*")]
        Act11.WSCS.ModificacionResponse Modificacion(Act11.WSCS.ModificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Act11.WSCS.ModificacionResponse> ModificacionAsync(Act11.WSCS.ModificacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento matricula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminacion", ReplyAction="*")]
        Act11.WSCS.EliminacionResponse Eliminacion(Act11.WSCS.EliminacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Act11.WSCS.EliminacionResponse> EliminacionAsync(Act11.WSCS.EliminacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento texto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encriptar", ReplyAction="*")]
        Act11.WSCS.EncriptarResponse Encriptar(Act11.WSCS.EncriptarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encriptar", ReplyAction="*")]
        System.Threading.Tasks.Task<Act11.WSCS.EncriptarResponse> EncriptarAsync(Act11.WSCS.EncriptarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento texto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Desencriptar", ReplyAction="*")]
        Act11.WSCS.DesencriptarResponse Desencriptar(Act11.WSCS.DesencriptarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Desencriptar", ReplyAction="*")]
        System.Threading.Tasks.Task<Act11.WSCS.DesencriptarResponse> DesencriptarAsync(Act11.WSCS.DesencriptarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insersion", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.InsersionRequestBody Body;
        
        public InsersionRequest() {
        }
        
        public InsersionRequest(Act11.WSCS.InsersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string matricula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string paterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string materno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string curp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rfc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int cveEstado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int cveMunicipio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int cveLocalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int rol;
        
        public InsersionRequestBody() {
        }
        
        public InsersionRequestBody(string matricula, string nombre, string paterno, string materno, string curp, string rfc, string sexo, int cveEstado, int cveMunicipio, int cveLocalidad, int rol) {
            this.matricula = matricula;
            this.nombre = nombre;
            this.paterno = paterno;
            this.materno = materno;
            this.curp = curp;
            this.rfc = rfc;
            this.sexo = sexo;
            this.cveEstado = cveEstado;
            this.cveMunicipio = cveMunicipio;
            this.cveLocalidad = cveLocalidad;
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.InsersionResponseBody Body;
        
        public InsersionResponse() {
        }
        
        public InsersionResponse(Act11.WSCS.InsersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsersionResult;
        
        public InsersionResponseBody() {
        }
        
        public InsersionResponseBody(string InsersionResult) {
            this.InsersionResult = InsersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificacion", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.ModificacionRequestBody Body;
        
        public ModificacionRequest() {
        }
        
        public ModificacionRequest(Act11.WSCS.ModificacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string matricula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string paterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string materno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string curp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rfc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int cveEstado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int cveMunicipio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int cveLocalidad;
        
        public ModificacionRequestBody() {
        }
        
        public ModificacionRequestBody(string matricula, string nombre, string paterno, string materno, string curp, string rfc, string sexo, int cveEstado, int cveMunicipio, int cveLocalidad) {
            this.matricula = matricula;
            this.nombre = nombre;
            this.paterno = paterno;
            this.materno = materno;
            this.curp = curp;
            this.rfc = rfc;
            this.sexo = sexo;
            this.cveEstado = cveEstado;
            this.cveMunicipio = cveMunicipio;
            this.cveLocalidad = cveLocalidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.ModificacionResponseBody Body;
        
        public ModificacionResponse() {
        }
        
        public ModificacionResponse(Act11.WSCS.ModificacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificacionResult;
        
        public ModificacionResponseBody() {
        }
        
        public ModificacionResponseBody(string ModificacionResult) {
            this.ModificacionResult = ModificacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminacion", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.EliminacionRequestBody Body;
        
        public EliminacionRequest() {
        }
        
        public EliminacionRequest(Act11.WSCS.EliminacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string matricula;
        
        public EliminacionRequestBody() {
        }
        
        public EliminacionRequestBody(string matricula) {
            this.matricula = matricula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.EliminacionResponseBody Body;
        
        public EliminacionResponse() {
        }
        
        public EliminacionResponse(Act11.WSCS.EliminacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminacionResult;
        
        public EliminacionResponseBody() {
        }
        
        public EliminacionResponseBody(string EliminacionResult) {
            this.EliminacionResult = EliminacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Encriptar", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.EncriptarRequestBody Body;
        
        public EncriptarRequest() {
        }
        
        public EncriptarRequest(Act11.WSCS.EncriptarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncriptarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        public EncriptarRequestBody() {
        }
        
        public EncriptarRequestBody(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncriptarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.EncriptarResponseBody Body;
        
        public EncriptarResponse() {
        }
        
        public EncriptarResponse(Act11.WSCS.EncriptarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncriptarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncriptarResult;
        
        public EncriptarResponseBody() {
        }
        
        public EncriptarResponseBody(string EncriptarResult) {
            this.EncriptarResult = EncriptarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DesencriptarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Desencriptar", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.DesencriptarRequestBody Body;
        
        public DesencriptarRequest() {
        }
        
        public DesencriptarRequest(Act11.WSCS.DesencriptarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DesencriptarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        public DesencriptarRequestBody() {
        }
        
        public DesencriptarRequestBody(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DesencriptarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DesencriptarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Act11.WSCS.DesencriptarResponseBody Body;
        
        public DesencriptarResponse() {
        }
        
        public DesencriptarResponse(Act11.WSCS.DesencriptarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DesencriptarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DesencriptarResult;
        
        public DesencriptarResponseBody() {
        }
        
        public DesencriptarResponseBody(string DesencriptarResult) {
            this.DesencriptarResult = DesencriptarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCSSoapChannel : Act11.WSCS.WSCSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCSSoapClient : System.ServiceModel.ClientBase<Act11.WSCS.WSCSSoap>, Act11.WSCS.WSCSSoap {
        
        public WSCSSoapClient() {
        }
        
        public WSCSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Act11.WSCS.InsersionResponse Act11.WSCS.WSCSSoap.Insersion(Act11.WSCS.InsersionRequest request) {
            return base.Channel.Insersion(request);
        }
        
        public string Insersion(string matricula, string nombre, string paterno, string materno, string curp, string rfc, string sexo, int cveEstado, int cveMunicipio, int cveLocalidad, int rol) {
            Act11.WSCS.InsersionRequest inValue = new Act11.WSCS.InsersionRequest();
            inValue.Body = new Act11.WSCS.InsersionRequestBody();
            inValue.Body.matricula = matricula;
            inValue.Body.nombre = nombre;
            inValue.Body.paterno = paterno;
            inValue.Body.materno = materno;
            inValue.Body.curp = curp;
            inValue.Body.rfc = rfc;
            inValue.Body.sexo = sexo;
            inValue.Body.cveEstado = cveEstado;
            inValue.Body.cveMunicipio = cveMunicipio;
            inValue.Body.cveLocalidad = cveLocalidad;
            inValue.Body.rol = rol;
            Act11.WSCS.InsersionResponse retVal = ((Act11.WSCS.WSCSSoap)(this)).Insersion(inValue);
            return retVal.Body.InsersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Act11.WSCS.InsersionResponse> Act11.WSCS.WSCSSoap.InsersionAsync(Act11.WSCS.InsersionRequest request) {
            return base.Channel.InsersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Act11.WSCS.InsersionResponse> InsersionAsync(string matricula, string nombre, string paterno, string materno, string curp, string rfc, string sexo, int cveEstado, int cveMunicipio, int cveLocalidad, int rol) {
            Act11.WSCS.InsersionRequest inValue = new Act11.WSCS.InsersionRequest();
            inValue.Body = new Act11.WSCS.InsersionRequestBody();
            inValue.Body.matricula = matricula;
            inValue.Body.nombre = nombre;
            inValue.Body.paterno = paterno;
            inValue.Body.materno = materno;
            inValue.Body.curp = curp;
            inValue.Body.rfc = rfc;
            inValue.Body.sexo = sexo;
            inValue.Body.cveEstado = cveEstado;
            inValue.Body.cveMunicipio = cveMunicipio;
            inValue.Body.cveLocalidad = cveLocalidad;
            inValue.Body.rol = rol;
            return ((Act11.WSCS.WSCSSoap)(this)).InsersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Act11.WSCS.ModificacionResponse Act11.WSCS.WSCSSoap.Modificacion(Act11.WSCS.ModificacionRequest request) {
            return base.Channel.Modificacion(request);
        }
        
        public string Modificacion(string matricula, string nombre, string paterno, string materno, string curp, string rfc, string sexo, int cveEstado, int cveMunicipio, int cveLocalidad) {
            Act11.WSCS.ModificacionRequest inValue = new Act11.WSCS.ModificacionRequest();
            inValue.Body = new Act11.WSCS.ModificacionRequestBody();
            inValue.Body.matricula = matricula;
            inValue.Body.nombre = nombre;
            inValue.Body.paterno = paterno;
            inValue.Body.materno = materno;
            inValue.Body.curp = curp;
            inValue.Body.rfc = rfc;
            inValue.Body.sexo = sexo;
            inValue.Body.cveEstado = cveEstado;
            inValue.Body.cveMunicipio = cveMunicipio;
            inValue.Body.cveLocalidad = cveLocalidad;
            Act11.WSCS.ModificacionResponse retVal = ((Act11.WSCS.WSCSSoap)(this)).Modificacion(inValue);
            return retVal.Body.ModificacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Act11.WSCS.ModificacionResponse> Act11.WSCS.WSCSSoap.ModificacionAsync(Act11.WSCS.ModificacionRequest request) {
            return base.Channel.ModificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Act11.WSCS.ModificacionResponse> ModificacionAsync(string matricula, string nombre, string paterno, string materno, string curp, string rfc, string sexo, int cveEstado, int cveMunicipio, int cveLocalidad) {
            Act11.WSCS.ModificacionRequest inValue = new Act11.WSCS.ModificacionRequest();
            inValue.Body = new Act11.WSCS.ModificacionRequestBody();
            inValue.Body.matricula = matricula;
            inValue.Body.nombre = nombre;
            inValue.Body.paterno = paterno;
            inValue.Body.materno = materno;
            inValue.Body.curp = curp;
            inValue.Body.rfc = rfc;
            inValue.Body.sexo = sexo;
            inValue.Body.cveEstado = cveEstado;
            inValue.Body.cveMunicipio = cveMunicipio;
            inValue.Body.cveLocalidad = cveLocalidad;
            return ((Act11.WSCS.WSCSSoap)(this)).ModificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Act11.WSCS.EliminacionResponse Act11.WSCS.WSCSSoap.Eliminacion(Act11.WSCS.EliminacionRequest request) {
            return base.Channel.Eliminacion(request);
        }
        
        public string Eliminacion(string matricula) {
            Act11.WSCS.EliminacionRequest inValue = new Act11.WSCS.EliminacionRequest();
            inValue.Body = new Act11.WSCS.EliminacionRequestBody();
            inValue.Body.matricula = matricula;
            Act11.WSCS.EliminacionResponse retVal = ((Act11.WSCS.WSCSSoap)(this)).Eliminacion(inValue);
            return retVal.Body.EliminacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Act11.WSCS.EliminacionResponse> Act11.WSCS.WSCSSoap.EliminacionAsync(Act11.WSCS.EliminacionRequest request) {
            return base.Channel.EliminacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Act11.WSCS.EliminacionResponse> EliminacionAsync(string matricula) {
            Act11.WSCS.EliminacionRequest inValue = new Act11.WSCS.EliminacionRequest();
            inValue.Body = new Act11.WSCS.EliminacionRequestBody();
            inValue.Body.matricula = matricula;
            return ((Act11.WSCS.WSCSSoap)(this)).EliminacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Act11.WSCS.EncriptarResponse Act11.WSCS.WSCSSoap.Encriptar(Act11.WSCS.EncriptarRequest request) {
            return base.Channel.Encriptar(request);
        }
        
        public string Encriptar(string texto) {
            Act11.WSCS.EncriptarRequest inValue = new Act11.WSCS.EncriptarRequest();
            inValue.Body = new Act11.WSCS.EncriptarRequestBody();
            inValue.Body.texto = texto;
            Act11.WSCS.EncriptarResponse retVal = ((Act11.WSCS.WSCSSoap)(this)).Encriptar(inValue);
            return retVal.Body.EncriptarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Act11.WSCS.EncriptarResponse> Act11.WSCS.WSCSSoap.EncriptarAsync(Act11.WSCS.EncriptarRequest request) {
            return base.Channel.EncriptarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Act11.WSCS.EncriptarResponse> EncriptarAsync(string texto) {
            Act11.WSCS.EncriptarRequest inValue = new Act11.WSCS.EncriptarRequest();
            inValue.Body = new Act11.WSCS.EncriptarRequestBody();
            inValue.Body.texto = texto;
            return ((Act11.WSCS.WSCSSoap)(this)).EncriptarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Act11.WSCS.DesencriptarResponse Act11.WSCS.WSCSSoap.Desencriptar(Act11.WSCS.DesencriptarRequest request) {
            return base.Channel.Desencriptar(request);
        }
        
        public string Desencriptar(string texto) {
            Act11.WSCS.DesencriptarRequest inValue = new Act11.WSCS.DesencriptarRequest();
            inValue.Body = new Act11.WSCS.DesencriptarRequestBody();
            inValue.Body.texto = texto;
            Act11.WSCS.DesencriptarResponse retVal = ((Act11.WSCS.WSCSSoap)(this)).Desencriptar(inValue);
            return retVal.Body.DesencriptarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Act11.WSCS.DesencriptarResponse> Act11.WSCS.WSCSSoap.DesencriptarAsync(Act11.WSCS.DesencriptarRequest request) {
            return base.Channel.DesencriptarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Act11.WSCS.DesencriptarResponse> DesencriptarAsync(string texto) {
            Act11.WSCS.DesencriptarRequest inValue = new Act11.WSCS.DesencriptarRequest();
            inValue.Body = new Act11.WSCS.DesencriptarRequestBody();
            inValue.Body.texto = texto;
            return ((Act11.WSCS.WSCSSoap)(this)).DesencriptarAsync(inValue);
        }
    }
}
